/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventofcode2018;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Day5 classUnderTest = new Day5();
        assertNotNull("app should have a greeting");
    }
}
